title: Maria Wellington
email: maria@wellingtonfamily.net
description: Academic and extracurricular portfolio for college applications.
baseurl: ""
url: ""
markdown: kramdown
theme: null
permalink: pretty

exclude:
  - "*.nix"
  - "README*"
  - "Gemfile"
  - "Gemfile.lock"
  - "*.toml"

collections: []
